services:
  todo-frontend:
    image: hello-front-dev
    environment:
      - VITE_BACKEND_URL=//localhost:3000
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3001:80
    container_name: reverse-proxy
    depends_on:
      todo-frontend:
        condition: service_started
        restart: true